"""
HIPAA / NIST CSF / HITRUST Control Library for Vendor Risk Assessment.

Contains 125 assessment questions mapped across three frameworks, organized
into 10 security domains. Each question carries a weight (1.0-3.0),
specifies applicable vendor types, and flags critical requirements under
the new HIPAA Security Rule updates.

Domains:
    1. Access Control & Authentication (20 questions)
    2. Encryption & Data Protection (15 questions)
    3. Audit & Monitoring (15 questions)
    4. Incident Response & Breach Notification (15 questions)
    5. Business Continuity & Disaster Recovery (10 questions)
    6. Physical & Environmental Security (10 questions)
    7. Vendor & Subcontractor Management (10 questions)
    8. Workforce Security & Training (10 questions)
    9. Vulnerability Management (10 questions)
   10. Network Security & Segmentation (10 questions)

VerifAI Security | Created by Nathan Mills
"""

from typing import List

from .models import AssessmentQuestion, VendorType

# Convenience: all vendor types
ALL_TYPES = list(VendorType)

# Vendor type groupings for applies_to filtering
DATA_HANDLERS = [
    VendorType.EHR_PROVIDER,
    VendorType.CLOUD_SERVICE,
    VendorType.BILLING_SERVICE,
    VendorType.CLEARINGHOUSE,
    VendorType.TELEHEALTH,
    VendorType.LAB_SYSTEM,
    VendorType.PHARMACY_SYSTEM,
    VendorType.IMAGING,
    VendorType.TRANSCRIPTION,
]

INFRASTRUCTURE = [
    VendorType.CLOUD_SERVICE,
    VendorType.IT_MANAGED_SERVICE,
    VendorType.EHR_PROVIDER,
]

CLINICAL_SYSTEMS = [
    VendorType.EHR_PROVIDER,
    VendorType.TELEHEALTH,
    VendorType.LAB_SYSTEM,
    VendorType.PHARMACY_SYSTEM,
    VendorType.IMAGING,
    VendorType.MEDICAL_DEVICE_MFG,
]

PHYSICAL_ACCESS = [
    VendorType.CLOUD_SERVICE,
    VendorType.IT_MANAGED_SERVICE,
    VendorType.DESTRUCTION_SERVICE,
    VendorType.MEDICAL_DEVICE_MFG,
]


# ============================================================================
# Domain 1: Access Control & Authentication (20 questions)
# ============================================================================

DOMAIN_1_ACCESS_CONTROL: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="AC-01",
        domain="Access Control & Authentication",
        subdomain="Unique User Identification",
        question_text="Does the vendor assign a unique user ID to each individual who accesses ePHI?",
        hipaa_reference="§164.312(a)(2)(i)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.b",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-02",
        domain="Access Control & Authentication",
        subdomain="Multi-Factor Authentication",
        question_text="Is multi-factor authentication (MFA) enforced for all users accessing systems containing ePHI?",
        hipaa_reference="§164.312(d)",
        nist_csf_reference="PR.AC-7",
        hitrust_reference="01.q",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-03",
        domain="Access Control & Authentication",
        subdomain="Role-Based Access Control",
        question_text="Does the vendor implement role-based access controls (RBAC) to limit ePHI access to the minimum necessary?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-4",
        hitrust_reference="01.c",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-04",
        domain="Access Control & Authentication",
        subdomain="Emergency Access Procedure",
        question_text="Has the vendor established and documented emergency access procedures for obtaining ePHI during an emergency?",
        hipaa_reference="§164.312(a)(2)(ii)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.b",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-05",
        domain="Access Control & Authentication",
        subdomain="Automatic Logoff",
        question_text="Does the vendor implement automatic logoff/session timeout for systems containing ePHI after a period of inactivity?",
        hipaa_reference="§164.312(a)(2)(iii)",
        nist_csf_reference="PR.AC-7",
        hitrust_reference="01.t",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-06",
        domain="Access Control & Authentication",
        subdomain="Session Timeout",
        question_text="Are session timeouts configured to 15 minutes or less for systems processing ePHI?",
        hipaa_reference="§164.312(a)(2)(iii)",
        nist_csf_reference="PR.AC-7",
        hitrust_reference="01.t",
        weight=1.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-07",
        domain="Access Control & Authentication",
        subdomain="Privilege Escalation Controls",
        question_text="Are privileged access accounts (admin, root) subject to enhanced controls including separate credentials and monitoring?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-4",
        hitrust_reference="01.c",
        weight=2.0,
        applies_to=INFRASTRUCTURE,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-08",
        domain="Access Control & Authentication",
        subdomain="Access Reviews",
        question_text="Does the vendor conduct periodic access reviews (at least quarterly) to ensure appropriate access levels?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.e",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-09",
        domain="Access Control & Authentication",
        subdomain="Account Provisioning",
        question_text="Is there a formal, documented process for provisioning and de-provisioning user accounts with appropriate approvals?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.b",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-10",
        domain="Access Control & Authentication",
        subdomain="Password Policy",
        question_text="Does the vendor enforce a strong password policy (minimum 12 characters, complexity requirements, no password reuse)?",
        hipaa_reference="§164.312(d)",
        nist_csf_reference="PR.AC-7",
        hitrust_reference="01.d",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-11",
        domain="Access Control & Authentication",
        subdomain="Account Lockout",
        question_text="Are account lockout mechanisms in place after a defined number of failed authentication attempts?",
        hipaa_reference="§164.312(d)",
        nist_csf_reference="PR.AC-7",
        hitrust_reference="01.p",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-12",
        domain="Access Control & Authentication",
        subdomain="Minimum Necessary",
        question_text="Does the vendor limit access to ePHI to only the minimum necessary information required for each user's job function?",
        hipaa_reference="§164.502(b)",
        nist_csf_reference="PR.AC-4",
        hitrust_reference="01.c",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-13",
        domain="Access Control & Authentication",
        subdomain="Remote Access",
        question_text="Are remote access connections to systems containing ePHI secured with VPN or equivalent encrypted channels and MFA?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-3",
        hitrust_reference="01.j",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-14",
        domain="Access Control & Authentication",
        subdomain="Service Accounts",
        question_text="Are service accounts and API keys managed with the same rigor as user accounts (rotation, least privilege, monitoring)?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.b",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-15",
        domain="Access Control & Authentication",
        subdomain="Termination Access Revocation",
        question_text="Are user accounts disabled within 24 hours of employee termination or role change?",
        hipaa_reference="§164.308(a)(3)(ii)(C)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.e",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-16",
        domain="Access Control & Authentication",
        subdomain="SSO Integration",
        question_text="Does the vendor support Single Sign-On (SSO) integration using SAML 2.0 or OpenID Connect for centralized authentication?",
        hipaa_reference="§164.312(d)",
        nist_csf_reference="PR.AC-7",
        hitrust_reference="01.q",
        weight=1.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-17",
        domain="Access Control & Authentication",
        subdomain="Break-Glass Procedures",
        question_text="Are break-glass (emergency override) access events logged, reviewed, and audited?",
        hipaa_reference="§164.312(a)(2)(ii)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.b",
        weight=1.5,
        applies_to=CLINICAL_SYSTEMS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-18",
        domain="Access Control & Authentication",
        subdomain="Shared Account Prohibition",
        question_text="Does the vendor prohibit shared/generic accounts for accessing systems that process ePHI?",
        hipaa_reference="§164.312(a)(2)(i)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="01.b",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AC-19",
        domain="Access Control & Authentication",
        subdomain="Mobile Device Management",
        question_text="Does the vendor enforce mobile device management (MDM) policies for any devices that access ePHI?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-3",
        hitrust_reference="01.x",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AC-20",
        domain="Access Control & Authentication",
        subdomain="Database Access Controls",
        question_text="Are direct database access controls in place to prevent unauthorized queries or extraction of ePHI data?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-4",
        hitrust_reference="01.c",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
]

# ============================================================================
# Domain 2: Encryption & Data Protection (15 questions)
# ============================================================================

DOMAIN_2_ENCRYPTION: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="EN-01",
        domain="Encryption & Data Protection",
        subdomain="Encryption at Rest",
        question_text="Is all ePHI encrypted at rest using AES-256 or equivalent FIPS 140-2 validated encryption?",
        hipaa_reference="§164.312(a)(2)(iv)",
        nist_csf_reference="PR.DS-1",
        hitrust_reference="06.d",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-02",
        domain="Encryption & Data Protection",
        subdomain="Encryption in Transit",
        question_text="Is all ePHI encrypted in transit using TLS 1.2 or higher?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.DS-2",
        hitrust_reference="09.m",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-03",
        domain="Encryption & Data Protection",
        subdomain="Key Management",
        question_text="Does the vendor maintain a formal encryption key management program including key generation, distribution, storage, rotation, and destruction?",
        hipaa_reference="§164.312(a)(2)(iv)",
        nist_csf_reference="PR.DS-1",
        hitrust_reference="06.d",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-04",
        domain="Encryption & Data Protection",
        subdomain="Data Loss Prevention",
        question_text="Does the vendor implement Data Loss Prevention (DLP) controls to detect and prevent unauthorized transmission of ePHI?",
        hipaa_reference="§164.312(e)(2)(ii)",
        nist_csf_reference="PR.DS-5",
        hitrust_reference="09.n",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-05",
        domain="Encryption & Data Protection",
        subdomain="Data Masking",
        question_text="Does the vendor use data masking or tokenization for ePHI in non-production environments (development, testing, training)?",
        hipaa_reference="§164.312(a)(2)(iv)",
        nist_csf_reference="PR.DS-5",
        hitrust_reference="06.d",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-06",
        domain="Encryption & Data Protection",
        subdomain="De-identification",
        question_text="Does the vendor support HIPAA-compliant de-identification methods (Safe Harbor or Expert Determination) when PHI must be shared for secondary purposes?",
        hipaa_reference="§164.514(a)-(b)",
        nist_csf_reference="PR.DS-5",
        hitrust_reference="06.d",
        weight=1.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-07",
        domain="Encryption & Data Protection",
        subdomain="Email Encryption",
        question_text="Is email containing ePHI encrypted using TLS, S/MIME, or an equivalent secure transport method?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.DS-2",
        hitrust_reference="09.m",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-08",
        domain="Encryption & Data Protection",
        subdomain="Backup Encryption",
        question_text="Are all backups containing ePHI encrypted to the same standard as production data?",
        hipaa_reference="§164.312(a)(2)(iv)",
        nist_csf_reference="PR.DS-1",
        hitrust_reference="06.d",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-09",
        domain="Encryption & Data Protection",
        subdomain="Portable Media Encryption",
        question_text="Is ePHI on portable media (USB drives, laptops, external drives) encrypted with full-disk or file-level encryption?",
        hipaa_reference="§164.312(a)(2)(iv)",
        nist_csf_reference="PR.DS-1",
        hitrust_reference="06.d",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-10",
        domain="Encryption & Data Protection",
        subdomain="Certificate Management",
        question_text="Does the vendor maintain a certificate management program to track, renew, and replace TLS/SSL certificates before expiration?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.DS-2",
        hitrust_reference="09.m",
        weight=1.0,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-11",
        domain="Encryption & Data Protection",
        subdomain="Secure Data Disposal",
        question_text="Does the vendor implement secure data disposal procedures (cryptographic erasure, NIST 800-88 compliant wiping) for media containing ePHI?",
        hipaa_reference="§164.310(d)(2)(i)",
        nist_csf_reference="PR.DS-3",
        hitrust_reference="08.l",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-12",
        domain="Encryption & Data Protection",
        subdomain="Data Classification",
        question_text="Does the vendor maintain a formal data classification policy that identifies and labels ePHI and sensitive data?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.DS-5",
        hitrust_reference="07.a",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-13",
        domain="Encryption & Data Protection",
        subdomain="Database Encryption",
        question_text="Are database fields containing ePHI encrypted at the column or field level (beyond full-disk encryption)?",
        hipaa_reference="§164.312(a)(2)(iv)",
        nist_csf_reference="PR.DS-1",
        hitrust_reference="06.d",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="EN-14",
        domain="Encryption & Data Protection",
        subdomain="API Security",
        question_text="Are APIs that transmit ePHI secured with encryption, authentication tokens, and rate limiting?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.DS-2",
        hitrust_reference="09.m",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="EN-15",
        domain="Encryption & Data Protection",
        subdomain="Data Retention",
        question_text="Does the vendor enforce documented data retention and destruction schedules aligned with HIPAA requirements (minimum 6 years for policies)?",
        hipaa_reference="§164.530(j)",
        nist_csf_reference="PR.DS-3",
        hitrust_reference="09.p",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
]

# ============================================================================
# Domain 3: Audit & Monitoring (15 questions)
# ============================================================================

DOMAIN_3_AUDIT: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="AU-01",
        domain="Audit & Monitoring",
        subdomain="Audit Trail Implementation",
        question_text="Does the vendor maintain comprehensive audit trails that record all access to and modifications of ePHI, including user ID, timestamp, and action performed?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-3",
        hitrust_reference="09.aa",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AU-02",
        domain="Audit & Monitoring",
        subdomain="Log Retention",
        question_text="Are audit logs retained for a minimum of 6 years, consistent with HIPAA documentation retention requirements?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-1",
        hitrust_reference="09.aa",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AU-03",
        domain="Audit & Monitoring",
        subdomain="Centralized Logging",
        question_text="Does the vendor utilize centralized log management (SIEM or equivalent) to aggregate and correlate security events across all systems?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.AE-3",
        hitrust_reference="09.ab",
        weight=2.0,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-04",
        domain="Audit & Monitoring",
        subdomain="Real-Time Alerting",
        question_text="Are real-time alerts configured for critical security events such as failed login attempts, privilege escalation, and unauthorized ePHI access?",
        hipaa_reference="§164.308(a)(1)(ii)(D)",
        nist_csf_reference="DE.AE-5",
        hitrust_reference="09.ab",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AU-05",
        domain="Audit & Monitoring",
        subdomain="Log Review Process",
        question_text="Does the vendor perform regular review of audit logs (at least weekly for critical systems) with documented procedures?",
        hipaa_reference="§164.308(a)(1)(ii)(D)",
        nist_csf_reference="DE.AE-2",
        hitrust_reference="09.aa",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AU-06",
        domain="Audit & Monitoring",
        subdomain="Suspicious Activity Detection",
        question_text="Does the vendor have mechanisms to detect and alert on suspicious activity patterns such as unusual data access volumes, off-hours access, or bulk downloads of ePHI?",
        hipaa_reference="§164.308(a)(1)(ii)(D)",
        nist_csf_reference="DE.CM-7",
        hitrust_reference="09.ab",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AU-07",
        domain="Audit & Monitoring",
        subdomain="Log Integrity",
        question_text="Are audit logs protected against unauthorized modification or deletion (immutable storage, integrity hashing, or write-once media)?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-3",
        hitrust_reference="09.aa",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="AU-08",
        domain="Audit & Monitoring",
        subdomain="Time Synchronization",
        question_text="Are all systems synchronized to an authoritative time source (NTP) to ensure accurate audit trail timestamps?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-1",
        hitrust_reference="09.aa",
        weight=1.0,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-09",
        domain="Audit & Monitoring",
        subdomain="Monitoring Coverage",
        question_text="Does monitoring coverage extend to all systems, applications, and network devices that process, store, or transmit ePHI?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-1",
        hitrust_reference="09.ab",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-10",
        domain="Audit & Monitoring",
        subdomain="User Activity Monitoring",
        question_text="Does the vendor monitor privileged user activity with enhanced logging and review procedures?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-3",
        hitrust_reference="09.aa",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-11",
        domain="Audit & Monitoring",
        subdomain="Anomaly Detection",
        question_text="Does the vendor employ behavioral analytics or anomaly detection to identify unusual patterns in ePHI access?",
        hipaa_reference="§164.308(a)(1)(ii)(D)",
        nist_csf_reference="DE.AE-1",
        hitrust_reference="09.ab",
        weight=1.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-12",
        domain="Audit & Monitoring",
        subdomain="Database Activity Monitoring",
        question_text="Is database activity monitoring (DAM) implemented to track direct database queries and changes to ePHI?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.CM-3",
        hitrust_reference="09.aa",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-13",
        domain="Audit & Monitoring",
        subdomain="Change Detection",
        question_text="Does the vendor implement file integrity monitoring (FIM) on systems that store ePHI?",
        hipaa_reference="§164.312(c)(2)",
        nist_csf_reference="DE.CM-6",
        hitrust_reference="09.aa",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-14",
        domain="Audit & Monitoring",
        subdomain="Audit Reporting",
        question_text="Can the vendor provide audit reports and log summaries to the covered entity upon request within a reasonable timeframe?",
        hipaa_reference="§164.312(b)",
        nist_csf_reference="DE.AE-4",
        hitrust_reference="12.d",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="AU-15",
        domain="Audit & Monitoring",
        subdomain="Endpoint Detection",
        question_text="Does the vendor deploy endpoint detection and response (EDR) solutions on workstations and servers that process ePHI?",
        hipaa_reference="§164.308(a)(1)(ii)(D)",
        nist_csf_reference="DE.CM-4",
        hitrust_reference="09.j",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
]

# ============================================================================
# Domain 4: Incident Response & Breach Notification (15 questions)
# ============================================================================

DOMAIN_4_INCIDENT_RESPONSE: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="IR-01",
        domain="Incident Response & Breach Notification",
        subdomain="IR Plan Documentation",
        question_text="Does the vendor maintain a documented incident response plan that specifically addresses ePHI breaches?",
        hipaa_reference="§164.308(a)(6)(i)",
        nist_csf_reference="RS.RP-1",
        hitrust_reference="11.a",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-02",
        domain="Incident Response & Breach Notification",
        subdomain="Breach Notification Timeline",
        question_text="Can the vendor notify the covered entity of a confirmed or suspected breach within 24 hours, as required by updated HIPAA rules?",
        hipaa_reference="§164.410",
        nist_csf_reference="RS.CO-2",
        hitrust_reference="11.a",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-03",
        domain="Incident Response & Breach Notification",
        subdomain="IR Plan Testing",
        question_text="Does the vendor conduct regular incident response plan testing (tabletop exercises or simulations) at least annually?",
        hipaa_reference="§164.308(a)(6)(i)",
        nist_csf_reference="RS.RP-1",
        hitrust_reference="11.c",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-04",
        domain="Incident Response & Breach Notification",
        subdomain="Forensic Capability",
        question_text="Does the vendor have access to digital forensics capabilities (internal team or contracted DFIR firm) for breach investigation?",
        hipaa_reference="§164.308(a)(6)(ii)",
        nist_csf_reference="RS.AN-1",
        hitrust_reference="11.b",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="IR-05",
        domain="Incident Response & Breach Notification",
        subdomain="Communication Plan",
        question_text="Does the vendor have a defined communication plan for notifying affected parties, including the covered entity, HHS, and potentially affected individuals?",
        hipaa_reference="§164.404-408",
        nist_csf_reference="RS.CO-1",
        hitrust_reference="11.a",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-06",
        domain="Incident Response & Breach Notification",
        subdomain="Post-Incident Review",
        question_text="Does the vendor conduct post-incident reviews (lessons learned) and implement corrective actions after security incidents?",
        hipaa_reference="§164.308(a)(6)(ii)",
        nist_csf_reference="RS.IM-1",
        hitrust_reference="11.c",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="IR-07",
        domain="Incident Response & Breach Notification",
        subdomain="Breach Risk Assessment",
        question_text="Does the vendor use a documented methodology to perform risk assessments of potential breaches to determine notification obligations?",
        hipaa_reference="§164.402",
        nist_csf_reference="RS.AN-2",
        hitrust_reference="11.a",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-08",
        domain="Incident Response & Breach Notification",
        subdomain="IR Team Roles",
        question_text="Does the vendor have a designated incident response team with clearly defined roles, responsibilities, and contact information?",
        hipaa_reference="§164.308(a)(6)(i)",
        nist_csf_reference="RS.CO-3",
        hitrust_reference="11.a",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="IR-09",
        domain="Incident Response & Breach Notification",
        subdomain="Evidence Preservation",
        question_text="Does the vendor have procedures for preserving evidence during security incidents to support potential legal proceedings or regulatory investigations?",
        hipaa_reference="§164.308(a)(6)(ii)",
        nist_csf_reference="RS.AN-3",
        hitrust_reference="11.b",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="IR-10",
        domain="Incident Response & Breach Notification",
        subdomain="Regulatory Reporting",
        question_text="Is the vendor familiar with and prepared to comply with HHS reporting requirements, including the 60-day notification deadline for breaches affecting 500+ individuals?",
        hipaa_reference="§164.408",
        nist_csf_reference="RS.CO-4",
        hitrust_reference="11.a",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-11",
        domain="Incident Response & Breach Notification",
        subdomain="Incident Classification",
        question_text="Does the vendor maintain a formal incident classification and severity system to prioritize response efforts?",
        hipaa_reference="§164.308(a)(6)(i)",
        nist_csf_reference="RS.AN-4",
        hitrust_reference="11.a",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="IR-12",
        domain="Incident Response & Breach Notification",
        subdomain="Containment Procedures",
        question_text="Does the vendor have documented containment procedures to isolate affected systems and prevent further ePHI exposure during an incident?",
        hipaa_reference="§164.308(a)(6)(ii)",
        nist_csf_reference="RS.MI-1",
        hitrust_reference="11.b",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-13",
        domain="Incident Response & Breach Notification",
        subdomain="Insurance Coverage",
        question_text="Does the vendor maintain cyber liability insurance that covers ePHI breach costs including notification, forensics, and regulatory fines?",
        hipaa_reference="§164.308(a)(6)",
        nist_csf_reference="RS.CO-5",
        hitrust_reference="11.a",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="IR-14",
        domain="Incident Response & Breach Notification",
        subdomain="Ransomware Response",
        question_text="Does the vendor have specific procedures for ransomware incidents including isolation, recovery from backups, and breach assessment?",
        hipaa_reference="§164.308(a)(6)(ii)",
        nist_csf_reference="RS.MI-2",
        hitrust_reference="11.b",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="IR-15",
        domain="Incident Response & Breach Notification",
        subdomain="Supply Chain Incident Notification",
        question_text="Does the vendor have procedures to notify the covered entity of security incidents at subcontractors or fourth parties that may affect ePHI?",
        hipaa_reference="§164.314(a)(2)(i)",
        nist_csf_reference="RS.CO-5",
        hitrust_reference="11.a",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
]

# ============================================================================
# Domain 5: Business Continuity & Disaster Recovery (10 questions)
# ============================================================================

DOMAIN_5_CONTINUITY: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="BC-01",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Continuity Plan",
        question_text="Does the vendor maintain a documented business continuity plan that addresses the availability of systems processing ePHI?",
        hipaa_reference="§164.308(a)(7)(i)",
        nist_csf_reference="PR.IP-9",
        hitrust_reference="12.a",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="BC-02",
        domain="Business Continuity & Disaster Recovery",
        subdomain="RPO/RTO Defined",
        question_text="Has the vendor defined Recovery Point Objectives (RPO) and Recovery Time Objectives (RTO) for systems containing ePHI?",
        hipaa_reference="§164.308(a)(7)(ii)(A)",
        nist_csf_reference="RC.RP-1",
        hitrust_reference="12.b",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="BC-03",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Backup Testing",
        question_text="Does the vendor regularly test data backups (at least quarterly) to verify successful restoration of ePHI?",
        hipaa_reference="§164.308(a)(7)(ii)(D)",
        nist_csf_reference="PR.IP-4",
        hitrust_reference="12.c",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="BC-04",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Geographic Redundancy",
        question_text="Does the vendor maintain geographically separated backup or disaster recovery sites for systems processing ePHI?",
        hipaa_reference="§164.308(a)(7)(ii)(B)",
        nist_csf_reference="RC.RP-1",
        hitrust_reference="12.b",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="BC-05",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Contingency Plan Activation Notification",
        question_text="Can the vendor notify the covered entity within 24 hours of activating its contingency plan, as required by updated HIPAA rules?",
        hipaa_reference="§164.308(a)(7)",
        nist_csf_reference="RC.CO-1",
        hitrust_reference="12.a",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="BC-06",
        domain="Business Continuity & Disaster Recovery",
        subdomain="DR Plan Testing",
        question_text="Does the vendor test its disaster recovery plan at least annually, including full failover tests for critical ePHI systems?",
        hipaa_reference="§164.308(a)(7)(ii)(D)",
        nist_csf_reference="RC.RP-1",
        hitrust_reference="12.c",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="BC-07",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Backup Encryption",
        question_text="Are backup copies of ePHI encrypted and stored securely with access controls equivalent to production systems?",
        hipaa_reference="§164.308(a)(7)(ii)(A)",
        nist_csf_reference="PR.IP-4",
        hitrust_reference="12.c",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="BC-08",
        domain="Business Continuity & Disaster Recovery",
        subdomain="SLA Commitments",
        question_text="Does the vendor provide documented service level agreements (SLAs) for system availability and recovery that meet the covered entity's needs?",
        hipaa_reference="§164.308(a)(7)(i)",
        nist_csf_reference="RC.RP-1",
        hitrust_reference="12.a",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="BC-09",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Dependency Mapping",
        question_text="Has the vendor identified and documented dependencies on third-party services and infrastructure critical to ePHI availability?",
        hipaa_reference="§164.308(a)(7)(ii)(E)",
        nist_csf_reference="ID.BE-4",
        hitrust_reference="12.a",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="BC-10",
        domain="Business Continuity & Disaster Recovery",
        subdomain="Data Integrity Verification",
        question_text="Does the vendor verify data integrity after restoration from backups to ensure ePHI has not been corrupted or lost?",
        hipaa_reference="§164.312(c)(1)",
        nist_csf_reference="RC.RP-1",
        hitrust_reference="12.c",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
]

# ============================================================================
# Domain 6: Physical & Environmental Security (10 questions)
# ============================================================================

DOMAIN_6_PHYSICAL: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="PE-01",
        domain="Physical & Environmental Security",
        subdomain="Facility Access Controls",
        question_text="Does the vendor implement physical access controls (badge readers, biometrics, mantraps) for facilities housing systems that process ePHI?",
        hipaa_reference="§164.310(a)(1)",
        nist_csf_reference="PR.AC-2",
        hitrust_reference="08.b",
        weight=2.0,
        applies_to=PHYSICAL_ACCESS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="PE-02",
        domain="Physical & Environmental Security",
        subdomain="Visitor Logging",
        question_text="Does the vendor maintain visitor logs and require escorts for non-authorized personnel in areas containing ePHI systems?",
        hipaa_reference="§164.310(a)(2)(iii)",
        nist_csf_reference="PR.AC-2",
        hitrust_reference="08.c",
        weight=1.5,
        applies_to=PHYSICAL_ACCESS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="PE-03",
        domain="Physical & Environmental Security",
        subdomain="Media Disposal",
        question_text="Does the vendor follow NIST 800-88 guidelines for sanitization of media containing ePHI prior to disposal or reuse?",
        hipaa_reference="§164.310(d)(2)(i)",
        nist_csf_reference="PR.IP-6",
        hitrust_reference="08.l",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="PE-04",
        domain="Physical & Environmental Security",
        subdomain="Device Inventory",
        question_text="Does the vendor maintain a complete, up-to-date inventory of all hardware assets that store, process, or transmit ePHI?",
        hipaa_reference="§164.310(d)(1)",
        nist_csf_reference="ID.AM-1",
        hitrust_reference="08.a",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="PE-05",
        domain="Physical & Environmental Security",
        subdomain="Workstation Security",
        question_text="Are workstations that access ePHI secured with screen locks, cable locks, and positioned to prevent unauthorized viewing?",
        hipaa_reference="§164.310(b)",
        nist_csf_reference="PR.AC-2",
        hitrust_reference="08.d",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="PE-06",
        domain="Physical & Environmental Security",
        subdomain="Environmental Controls",
        question_text="Are data centers and server rooms equipped with environmental controls (fire suppression, HVAC, water detection, UPS)?",
        hipaa_reference="§164.310(a)(2)(ii)",
        nist_csf_reference="PR.IP-5",
        hitrust_reference="08.g",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="PE-07",
        domain="Physical & Environmental Security",
        subdomain="CCTV & Surveillance",
        question_text="Are facilities housing ePHI systems monitored by CCTV or equivalent surveillance with appropriate retention of footage?",
        hipaa_reference="§164.310(a)(1)",
        nist_csf_reference="PR.AC-2",
        hitrust_reference="08.b",
        weight=1.0,
        applies_to=PHYSICAL_ACCESS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="PE-08",
        domain="Physical & Environmental Security",
        subdomain="Secure Areas",
        question_text="Are areas with concentrated ePHI processing (data centers, MDF/IDF closets) designated as secure areas with restricted access?",
        hipaa_reference="§164.310(a)(1)",
        nist_csf_reference="PR.AC-2",
        hitrust_reference="08.b",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="PE-09",
        domain="Physical & Environmental Security",
        subdomain="Device Movement",
        question_text="Does the vendor track and authorize all movement of hardware and electronic media containing ePHI in and out of facilities?",
        hipaa_reference="§164.310(d)(1)",
        nist_csf_reference="PR.DS-3",
        hitrust_reference="08.k",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="PE-10",
        domain="Physical & Environmental Security",
        subdomain="Clean Desk Policy",
        question_text="Does the vendor enforce a clean desk policy to prevent unauthorized access to ePHI in printed or written form?",
        hipaa_reference="§164.310(c)",
        nist_csf_reference="PR.AC-2",
        hitrust_reference="08.d",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
]

# ============================================================================
# Domain 7: Vendor & Subcontractor Management (10 questions)
# ============================================================================

DOMAIN_7_SUBCONTRACTORS: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="VM-01",
        domain="Vendor & Subcontractor Management",
        subdomain="Subcontractor BAA Flow-Down",
        question_text="Does the vendor require all subcontractors who access ePHI to execute Business Associate Agreements with equivalent protections?",
        hipaa_reference="§164.314(a)(2)(i)",
        nist_csf_reference="ID.SC-3",
        hitrust_reference="05.i",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VM-02",
        domain="Vendor & Subcontractor Management",
        subdomain="Fourth-Party Risk Visibility",
        question_text="Does the vendor maintain a current inventory of all subcontractors (fourth parties) that have access to or process the covered entity's ePHI?",
        hipaa_reference="§164.308(b)(1)",
        nist_csf_reference="ID.SC-2",
        hitrust_reference="05.i",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VM-03",
        domain="Vendor & Subcontractor Management",
        subdomain="Subcontractor Risk Assessment",
        question_text="Does the vendor conduct security assessments of its subcontractors before granting them access to ePHI?",
        hipaa_reference="§164.308(b)(1)",
        nist_csf_reference="ID.SC-4",
        hitrust_reference="05.k",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VM-04",
        domain="Vendor & Subcontractor Management",
        subdomain="Subcontractor Monitoring",
        question_text="Does the vendor perform ongoing monitoring of subcontractor security posture and compliance?",
        hipaa_reference="§164.308(b)(1)",
        nist_csf_reference="ID.SC-4",
        hitrust_reference="05.k",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VM-05",
        domain="Vendor & Subcontractor Management",
        subdomain="Vendor Access Reviews",
        question_text="Does the vendor conduct periodic reviews of subcontractor access to ePHI and remove access that is no longer required?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.AC-1",
        hitrust_reference="05.i",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VM-06",
        domain="Vendor & Subcontractor Management",
        subdomain="Termination Procedures",
        question_text="Does the vendor have documented procedures to revoke subcontractor access and ensure ePHI return/destruction upon contract termination?",
        hipaa_reference="§164.314(a)(2)(ii)",
        nist_csf_reference="ID.SC-5",
        hitrust_reference="05.i",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VM-07",
        domain="Vendor & Subcontractor Management",
        subdomain="Notification of Changes",
        question_text="Does the vendor notify the covered entity before introducing new subcontractors that will have access to ePHI?",
        hipaa_reference="§164.314(a)",
        nist_csf_reference="ID.SC-1",
        hitrust_reference="05.i",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VM-08",
        domain="Vendor & Subcontractor Management",
        subdomain="Data Processing Locations",
        question_text="Does the vendor disclose all locations (including subcontractor facilities) where ePHI is processed, stored, or transmitted?",
        hipaa_reference="§164.314(a)",
        nist_csf_reference="ID.SC-2",
        hitrust_reference="05.i",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VM-09",
        domain="Vendor & Subcontractor Management",
        subdomain="Supply Chain Security",
        question_text="Does the vendor assess and mitigate supply chain risks for software components and services used in ePHI processing?",
        hipaa_reference="§164.308(b)(1)",
        nist_csf_reference="ID.SC-1",
        hitrust_reference="05.k",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VM-10",
        domain="Vendor & Subcontractor Management",
        subdomain="Offshore Processing Disclosure",
        question_text="Does the vendor disclose if any ePHI is processed, stored, or accessible from locations outside the United States?",
        hipaa_reference="§164.314(a)",
        nist_csf_reference="ID.SC-2",
        hitrust_reference="05.i",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
]

# ============================================================================
# Domain 8: Workforce Security & Training (10 questions)
# ============================================================================

DOMAIN_8_WORKFORCE: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="WF-01",
        domain="Workforce Security & Training",
        subdomain="Background Checks",
        question_text="Does the vendor conduct background checks on all employees who will have access to ePHI?",
        hipaa_reference="§164.308(a)(3)(ii)(B)",
        nist_csf_reference="PR.AT-5",
        hitrust_reference="02.b",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="WF-02",
        domain="Workforce Security & Training",
        subdomain="Security Awareness Training",
        question_text="Does the vendor provide annual security awareness training to all workforce members that covers HIPAA requirements and ePHI handling?",
        hipaa_reference="§164.308(a)(5)(i)",
        nist_csf_reference="PR.AT-1",
        hitrust_reference="02.e",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="WF-03",
        domain="Workforce Security & Training",
        subdomain="Role-Based Training",
        question_text="Does the vendor provide role-specific security training for technical staff, administrators, and others with elevated ePHI access?",
        hipaa_reference="§164.308(a)(5)(ii)(A)",
        nist_csf_reference="PR.AT-2",
        hitrust_reference="02.e",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="WF-04",
        domain="Workforce Security & Training",
        subdomain="Phishing Testing",
        question_text="Does the vendor conduct regular phishing simulation exercises to test employee awareness and response?",
        hipaa_reference="§164.308(a)(5)(ii)(A)",
        nist_csf_reference="PR.AT-1",
        hitrust_reference="02.e",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="WF-05",
        domain="Workforce Security & Training",
        subdomain="Termination Procedures",
        question_text="Does the vendor have documented termination procedures that include immediate revocation of all access to ePHI systems?",
        hipaa_reference="§164.308(a)(3)(ii)(C)",
        nist_csf_reference="PR.AT-5",
        hitrust_reference="02.c",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="WF-06",
        domain="Workforce Security & Training",
        subdomain="Acceptable Use Policy",
        question_text="Does the vendor maintain and enforce an acceptable use policy governing the use of systems and data including ePHI?",
        hipaa_reference="§164.308(a)(5)(ii)(C)",
        nist_csf_reference="PR.AT-1",
        hitrust_reference="02.a",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="WF-07",
        domain="Workforce Security & Training",
        subdomain="Confidentiality Agreements",
        question_text="Does the vendor require all workforce members with ePHI access to sign confidentiality/non-disclosure agreements?",
        hipaa_reference="§164.308(a)(3)(ii)(A)",
        nist_csf_reference="PR.AT-5",
        hitrust_reference="02.d",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="WF-08",
        domain="Workforce Security & Training",
        subdomain="Training Records",
        question_text="Does the vendor maintain training completion records that can be provided as evidence of workforce compliance?",
        hipaa_reference="§164.530(j)",
        nist_csf_reference="PR.AT-1",
        hitrust_reference="02.e",
        weight=1.0,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="WF-09",
        domain="Workforce Security & Training",
        subdomain="Sanctions Policy",
        question_text="Does the vendor maintain and enforce a sanctions policy for workforce members who violate security policies or HIPAA requirements?",
        hipaa_reference="§164.308(a)(1)(ii)(C)",
        nist_csf_reference="PR.AT-5",
        hitrust_reference="02.d",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="WF-10",
        domain="Workforce Security & Training",
        subdomain="New Hire Training",
        question_text="Does the vendor require HIPAA and security awareness training for all new hires before granting access to ePHI systems?",
        hipaa_reference="§164.308(a)(5)(i)",
        nist_csf_reference="PR.AT-1",
        hitrust_reference="02.e",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
]

# ============================================================================
# Domain 9: Vulnerability Management (10 questions)
# ============================================================================

DOMAIN_9_VULNERABILITY: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="VU-01",
        domain="Vulnerability Management",
        subdomain="Vulnerability Scanning",
        question_text="Does the vendor perform vulnerability scanning at least semi-annually (every 6 months), as required by updated HIPAA rules?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="DE.CM-8",
        hitrust_reference="10.m",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VU-02",
        domain="Vulnerability Management",
        subdomain="Penetration Testing",
        question_text="Does the vendor conduct annual penetration testing of systems that process ePHI, as required by updated HIPAA rules?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="DE.CM-8",
        hitrust_reference="10.m",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VU-03",
        domain="Vulnerability Management",
        subdomain="Patch Management",
        question_text="Does the vendor have a documented patch management program with defined SLAs (critical patches within 14 days, high within 30 days)?",
        hipaa_reference="§164.308(a)(1)(ii)(A)",
        nist_csf_reference="RS.MI-3",
        hitrust_reference="10.m",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VU-04",
        domain="Vulnerability Management",
        subdomain="Remediation Tracking",
        question_text="Does the vendor track vulnerability remediation efforts with documented timelines and escalation procedures for overdue items?",
        hipaa_reference="§164.308(a)(1)(ii)(B)",
        nist_csf_reference="RS.MI-3",
        hitrust_reference="10.m",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VU-05",
        domain="Vulnerability Management",
        subdomain="SBOM Maintenance",
        question_text="Does the vendor maintain a Software Bill of Materials (SBOM) for applications that process ePHI to track third-party component vulnerabilities?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="ID.AM-2",
        hitrust_reference="10.m",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VU-06",
        domain="Vulnerability Management",
        subdomain="Scan Results Sharing",
        question_text="Can the vendor share vulnerability scan results or executive summaries with the covered entity upon request?",
        hipaa_reference="§164.308(a)(1)(ii)(A)",
        nist_csf_reference="DE.CM-8",
        hitrust_reference="10.m",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VU-07",
        domain="Vulnerability Management",
        subdomain="Web Application Security",
        question_text="Does the vendor perform web application security testing (OWASP Top 10) for any web-based systems that handle ePHI?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="DE.CM-8",
        hitrust_reference="10.m",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VU-08",
        domain="Vulnerability Management",
        subdomain="End-of-Life Management",
        question_text="Does the vendor have a process to identify and replace end-of-life (EOL) software and hardware that no longer receives security updates?",
        hipaa_reference="§164.308(a)(1)(ii)(A)",
        nist_csf_reference="PR.IP-12",
        hitrust_reference="10.m",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="VU-09",
        domain="Vulnerability Management",
        subdomain="Threat Intelligence",
        question_text="Does the vendor subscribe to and act on threat intelligence feeds relevant to healthcare and ePHI-processing systems?",
        hipaa_reference="§164.308(a)(1)(ii)(A)",
        nist_csf_reference="DE.CM-8",
        hitrust_reference="10.m",
        weight=1.0,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="VU-10",
        domain="Vulnerability Management",
        subdomain="Secure Development",
        question_text="Does the vendor follow secure software development lifecycle (SSDLC) practices including code review and static analysis for applications processing ePHI?",
        hipaa_reference="§164.312(a)(1)",
        nist_csf_reference="PR.IP-2",
        hitrust_reference="10.a",
        weight=1.5,
        applies_to=DATA_HANDLERS,
        is_critical=False,
    ),
]

# ============================================================================
# Domain 10: Network Security & Segmentation (10 questions)
# ============================================================================

DOMAIN_10_NETWORK: List[AssessmentQuestion] = [
    AssessmentQuestion(
        id="NS-01",
        domain="Network Security & Segmentation",
        subdomain="Network Segmentation",
        question_text="Does the vendor implement network segmentation to isolate systems processing ePHI from general-purpose networks, as required by updated HIPAA rules?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-5",
        hitrust_reference="09.f",
        weight=3.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="NS-02",
        domain="Network Security & Segmentation",
        subdomain="Firewall Rules",
        question_text="Are firewall rules documented, reviewed at least annually, and configured to deny all traffic by default (allowlist approach)?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-5",
        hitrust_reference="09.f",
        weight=2.0,
        applies_to=INFRASTRUCTURE,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="NS-03",
        domain="Network Security & Segmentation",
        subdomain="Wireless Security",
        question_text="Are wireless networks secured with WPA3 (or WPA2-Enterprise minimum) and segmented from networks containing ePHI?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-5",
        hitrust_reference="09.f",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="NS-04",
        domain="Network Security & Segmentation",
        subdomain="Remote Access Controls",
        question_text="Are remote access connections to the vendor's network restricted to authorized methods (VPN, zero-trust) with MFA and logging?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-3",
        hitrust_reference="09.m",
        weight=2.0,
        applies_to=ALL_TYPES,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="NS-05",
        domain="Network Security & Segmentation",
        subdomain="IDS/IPS Deployment",
        question_text="Does the vendor deploy intrusion detection/prevention systems (IDS/IPS) to monitor network traffic for malicious activity targeting ePHI systems?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="DE.CM-1",
        hitrust_reference="09.f",
        weight=2.0,
        applies_to=INFRASTRUCTURE,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="NS-06",
        domain="Network Security & Segmentation",
        subdomain="DNS Security",
        question_text="Does the vendor implement DNS security measures (DNSSEC, DNS filtering) to protect against DNS-based attacks?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.DS-5",
        hitrust_reference="09.f",
        weight=1.0,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="NS-07",
        domain="Network Security & Segmentation",
        subdomain="Network Access Control",
        question_text="Does the vendor implement network access control (NAC) to prevent unauthorized devices from connecting to networks with ePHI?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-5",
        hitrust_reference="09.f",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="NS-08",
        domain="Network Security & Segmentation",
        subdomain="Micro-Segmentation",
        question_text="Does the vendor implement micro-segmentation or zero-trust network architecture for critical ePHI processing environments?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.AC-5",
        hitrust_reference="09.f",
        weight=1.5,
        applies_to=INFRASTRUCTURE,
        is_critical=False,
    ),
    AssessmentQuestion(
        id="NS-09",
        domain="Network Security & Segmentation",
        subdomain="Outbound Traffic Filtering",
        question_text="Does the vendor monitor and restrict outbound network traffic from ePHI systems to prevent data exfiltration?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="PR.DS-5",
        hitrust_reference="09.m",
        weight=2.0,
        applies_to=DATA_HANDLERS,
        is_critical=True,
    ),
    AssessmentQuestion(
        id="NS-10",
        domain="Network Security & Segmentation",
        subdomain="Network Diagram Documentation",
        question_text="Does the vendor maintain current, accurate network diagrams showing ePHI data flows, segmentation boundaries, and external connections?",
        hipaa_reference="§164.312(e)(1)",
        nist_csf_reference="ID.AM-3",
        hitrust_reference="09.f",
        weight=1.5,
        applies_to=ALL_TYPES,
        is_critical=False,
    ),
]


# ============================================================================
# Complete Control Library
# ============================================================================

CONTROL_LIBRARY: List[AssessmentQuestion] = (
    DOMAIN_1_ACCESS_CONTROL
    + DOMAIN_2_ENCRYPTION
    + DOMAIN_3_AUDIT
    + DOMAIN_4_INCIDENT_RESPONSE
    + DOMAIN_5_CONTINUITY
    + DOMAIN_6_PHYSICAL
    + DOMAIN_7_SUBCONTRACTORS
    + DOMAIN_8_WORKFORCE
    + DOMAIN_9_VULNERABILITY
    + DOMAIN_10_NETWORK
)

# Lookup index by question ID
CONTROL_INDEX: dict = {q.id: q for q in CONTROL_LIBRARY}

# All domain names in order
DOMAINS: List[str] = [
    "Access Control & Authentication",
    "Encryption & Data Protection",
    "Audit & Monitoring",
    "Incident Response & Breach Notification",
    "Business Continuity & Disaster Recovery",
    "Physical & Environmental Security",
    "Vendor & Subcontractor Management",
    "Workforce Security & Training",
    "Vulnerability Management",
    "Network Security & Segmentation",
]


def get_questions_for_vendor(
    vendor_type: VendorType,
    phi_access: bool = True,
) -> List[AssessmentQuestion]:
    """
    Filter the control library to questions applicable to a specific vendor.

    Args:
        vendor_type: The vendor's VendorType classification.
        phi_access: Whether the vendor has access to PHI. If False, only
                    non-PHI-specific questions are returned plus any that
                    apply to all vendor types.

    Returns:
        Filtered list of AssessmentQuestion instances applicable to this vendor.
    """
    applicable = []
    for question in CONTROL_LIBRARY:
        # Check if vendor type is in the applies_to list
        if vendor_type in question.applies_to:
            applicable.append(question)

    # If vendor has no PHI access, exclude PHI-specific data handling questions
    # but keep infrastructure, workforce, and general security controls
    if not phi_access:
        non_phi_domains = {
            "Physical & Environmental Security",
            "Workforce Security & Training",
            "Network Security & Segmentation",
        }
        applicable = [
            q for q in applicable
            if q.domain in non_phi_domains
            or q.weight >= 2.0  # Keep critical controls regardless
            or "ePHI" not in q.question_text
        ]

    return applicable


def get_questions_by_domain(domain: str) -> List[AssessmentQuestion]:
    """
    Get all questions for a specific domain.

    Args:
        domain: The domain name (must match one of DOMAINS).

    Returns:
        List of questions in that domain.
    """
    return [q for q in CONTROL_LIBRARY if q.domain == domain]


def get_critical_questions() -> List[AssessmentQuestion]:
    """
    Get all questions marked as critical (mandatory under new HIPAA rules).

    Returns:
        List of critical AssessmentQuestion instances.
    """
    return [q for q in CONTROL_LIBRARY if q.is_critical]


def get_question(question_id: str) -> AssessmentQuestion:
    """
    Look up a question by its ID.

    Args:
        question_id: The question identifier (e.g., "AC-01").

    Returns:
        The AssessmentQuestion.

    Raises:
        KeyError: If question_id is not found.
    """
    if question_id not in CONTROL_INDEX:
        raise KeyError(f"Question '{question_id}' not found in control library")
    return CONTROL_INDEX[question_id]
